### ISSUE TITLE
Failing to connect to a database doesn't show an error in the UI

### ISSUE THREAD

**Issue by joshuataylor** [livebook-dev/kino_db#14]
Mistyping the credentials just returns an `{:ok, #PID<xxx.x>}`, and no error.

![image](https://user-images.githubusercontent.com/225131/170858079-40874831-014b-47b1-91ee-4d18a7e9f5d4.png)

The user then assumes that they can then go and query, but they get an error.

On the command line this shows correctly (as it logs the error):
![image](https://user-images.githubusercontent.com/225131/170858124-8fbea06f-72b4-4631-bb88-d95ece96fdf9.png)

**Comment by josevalim** [comment]
We are tracking this one here: https://github.com/livebook-dev/livebook/issues/1162 :) Thank you!
