### ISSUE TITLE
Paged/Chunked results

### ISSUE THREAD

**Issue by joshuataylor** [livebook-dev/kino_db#17]
This is relevant to Snowflake, and probably others as well.

When a user does `select * from foobar`, Snowflake sends you the initial rowset in a base64 encoded string, then the others as JSON/Arrow chunks. This allows you to show the user the initial result and then download the chunks if you need them. The chunks are listed in the query response, and contains a list of chunks with the file size & rowset size.

Database tools like Datagrip for example when using Snowflake will only show what's returned via the rowset, and if you require more it'll download the chunks as needed. When using other databases it does a limit of the responses.

Should we do something similar, where we show how many results were returned, but not actually download/parse all the results, unless the user requires it in a follow up step (lazy execution) or goes to another page in the table where it doesn't have results?

**Comment by josevalim** [comment]
@joshuataylor do you know how large is the initial rowset?

Also, how are those chunks written? Per column? Or do you have different columns in the same chunk/S3 file?

KinoDB expects a data structure that implements Table and Table supports for laziness, but cross-columns laziness would be tricky at the moment, hence the questions!

**Comment by joshuataylor** [comment]
These chunks contain all columns with a consistent length so you can get a table view if needed per chunk and same for the initial baseset.

Returning a table is fine.

**Comment by josevalim** [comment]
I have one additional question: if we ask you for range “1000..1100”, do you know exactly which files you need to load?

Meanwhile I talked to @jonatanklosko and we need three things to make this happen:

1. we need to make Kino.DataTable lazy in how it handles Enum
2. We need to support an initialized Table.Reader as arguments to table
3. We need to support annotated metadata in Explorer.DataFrame.new
