### ISSUE TITLE
[Question] Support DuckDB

### ISSUE THREAD

**Issue by sweco-semtne** [livebook-dev/kino_db#23]
Hi!
I wonder if there are any plans to support [DuckDB](https://duckdb.org)
Given its OLAP capabilities it seems like a good fit?

**Comment by josevalim** [comment]
Hi @sweco-semtne, we don't plan to support such officially for now, but you should be able to provide your own smart cells/functionality around it. Contributions to make the current design extensible to external packages if necessary is also welcome. Thanks!

**Comment by josevalim** [comment]
In case someone runs into this from a search engine, we do support DuckDB in Livebook: https://github.com/livebook-dev/kino_db/pull/71
