### ISSUE TITLE
Provide a warning if there are no database connections available before query

### ISSUE THREAD

**Issue by josevalim** [livebook-dev/kino_db#4]
The warning should ask users to click the "+ Smart" button and establish a database connection, similar to how it is done in the chart builder:

<img width="920" alt="image" src="https://user-images.githubusercontent.com/9582/168280860-c6e6e0ae-f277-4e85-b0b8-df9b135dee3d.png">

**Comment by aleDsz** [comment]
![Screenshot_20220527_142357](https://user-images.githubusercontent.com/6402997/170760295-1f011791-e740-4f01-9fb8-924fea185ae3.png)

WDYT?

**Comment by josevalim** [comment]
What do you mean by:

> With an outdated database connection but not reevaluated:

Does this mean the previous cell is outdated? I don't think we need to show anything because evaluating will automatically fix the error.

**Comment by aleDsz** [comment]
> What do you mean by:
> 
> > With an outdated database connection but not reevaluated:
> 
> Does this mean the previous cell is outdated? I don't think we need to show anything because evaluating will automatically fix the error.

Yeah, I was thinking if we should show for this case, but then I'll remove and open a PR
