### ISSUE TITLE
Support UUID 

### ISSUE THREAD

**Issue by LostKobrakai** [livebook-dev/kino_db#56]
When trying to query a table with uuid primary key with postgrex (`SELECT * FROM table`) I get this error:
```
Failed to serialize initial widget data, invalid byte 0xD0 in <<208, 115, 222, 115, 28, 225, 73, 163, 144, 184, 76, 109, 162, 124, 182, 190>>
```

**Comment by LostKobrakai** [comment]
As a workaround this seems to work `SELECT id::text FROM table`, but that also means one can no longer use `*`.

**Comment by jonatanklosko** [comment]
Raw UUID is binary and encoding it as JSON string fails. See https://github.com/livebook-dev/kino/issues/192.

**Comment by mbaltrusitis** [comment]
> As a workaround this seems to work `SELECT id::text FROM table`, but that also means one can no longer use `*`.

And for the mirrored workaround where you want to use the output of `table.id::text` as an input to a future query:

```
WHERE table.id::text = {{some_value}}
```

Because the following will not work:

```
WHERE table.id = {{some_value}}::uuid
```

**Comment by josevalim** [comment]
I think improving the error message can be a good call. @jonatanklosko, do we know the smart cell that triggered the error in Livebook?

**Comment by mbaltrusitis** [comment]
> I think improving the error message can be a good call. @jonatanklosko, do we know the smart cell that triggered the error in Livebook?

I can reproduce this using a `SQL Query` Smart Cell.

**Comment by jonatanklosko** [comment]
@josevalim it's not specific to smart cell, the query returns `%Postgrex.Result{}`, which we render as `Kino.DataTable`, which from Livebook perspective is just `Kino.JS.Live`, so Livebook gets the data and then tries to serialize it to send it to the iframe. So if we want to add a special-cased error it needs to be more generic:

<img width="915" alt="image" src="https://github.com/livebook-dev/kino_db/assets/17034772/78177efc-72d1-4ad0-8fb9-f849302b0632">

**Comment by josevalim** [comment]
@jonatanklosko it is either a better error message OR we implement this issue: https://github.com/michalmuskala/jason/issues/12. But that means the UUID above would be rendered as `�s�s^<�I�Lm�|�` which is hardly helpful.

**Comment by jonatanklosko** [comment]
I've just realised it's not really about UUID, the issue is just that Kino.DataTable doesn't inspect non-utf8 binaries, which we can easily do. See https://github.com/livebook-dev/kino/pull/362.
