### ISSUE TITLE
explorer 0.8.0 is not supported

### ISSUE THREAD

**Issue by sdball** [livebook-dev/kino_db#69]
Trying to use both `kino_db` and `explorer` in a LiveBook results in an error because kino_db depends on explorer 0.7.0 and the latest explorer is 0.8.0. Manually fixable for sure, but it would be nice to allow the latest version.

**Comment by josevalim** [comment]
Done!

**Comment by sdball** [comment]
TYVM! ❤️

**Comment by sdball** [comment]
And TIL dependencies can have an `or` whoa
