### ISSUE TITLE
SQL Variable Injection WHERE IN Clauses

### ISSUE THREAD

**Issue by rcuevas-wash** [livebook-dev/kino_db#76]
## Environment

Elixir 1.16.2 (compiled with Erlang/OTP 26)
* Windows
* Livebook APP
* v0.14.0-rc.1

## Current behavior
SQL Intgration, MSSQL
When you want to filter On multiple values for a column such as:

SELECT *
FROM users 
WHERE id IN ( {{ user_ids }} )

It is not clear how to pass a collection into  IN  (...)
Arrays, tuples, char lists, strings..  there is no data type or collection of data types that allows one to do  this type of query successfully.
It returns the  following error:

** (FunctionClauseError) no function clause matching in Tds.Parameter.fix_data_type/1    

## Expected behavior

user_ids can be any of the following values:

[ '5', '6' ],
"'5', '6'",
"\"5\", \"6\"",
{ '5','6' }.. etc etc

And so the following query would work:

SELECT *
FROM users 
WHERE id IN ( {{ user_ids }} )

**Comment by jonatanklosko** [comment]
> we could try to generate the SQL dynamically but that would require us to read the value (the list size) at the time we generate code, and I am not quite sure if it is possible?

@josevalim we could scan the binding to know which variables are lists, so we could special case `{{list_var}}`. That's not reliable though, because someone can do `{{Enum.map(...)}}` and we wouldn't know it's a list. Handling one case without the other doesn't seem correct.

**Comment by jonatanklosko** [comment]
@rcuevas-wash oh, I think it's supposed to be `Enum.join(user_ids, ",")`, please try that :D

**Comment by rcuevas-wash** [comment]
No Cigar. 
Im going to in the meantime  do the filtering in elixir for multiple values.

**Comment by jonatanklosko** [comment]
@rcuevas-wash to make sure we are on the same page, can you try this query?

```sql
SELECT * FROM sys.Databases
WHERE database_id IN (SELECT value FROM STRING_SPLIT({{ Enum.join(ids, ",") }}, ','))
```

Seems to be working as expected for me:

<img width="459" alt="image" src="https://github.com/user-attachments/assets/6decade7-e14a-4c5c-b9b4-10f2d739b0b7">

FTR, I am using this image:

```
docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=reallyStrongPwd123" \
  -p 1433:1433 --name sql2022 --hostname sql2022 \
  --rm \
  mcr.microsoft.com/mssql/server:2022-latest
```

**Comment by rcuevas-wash** [comment]
This works.
Can close
Thank you !
